# Generated by Django 2.1.2 on 2018-10-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fringe_api', '0006_auto_20181031_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
